### ISSUE TITLE
[Feature request] Uniform with number of frame

### ISSUE THREAD

**Issue by illus0r** [doxas/twigl#15]
Thank you for the amazing tool, I use it almost every day. Would be really handy to have the frame count uniform, like iFrame on Shadertoy. What's your take on that?

**Comment by doxas** [comment]
@illus0r 

Thanks for always using twigl!

It is possible, and not too difficult, to provide a variable equivalent to Shadertoy's `iFrame`.
However, the question is what to name the variable.

Since twigl has multiple regulations, we need to define variables with appropriate names for each.
We also need to make sure that there is as little overlap as possible with the variable names declared by the user.

I think it would be reasonable to use `frame` for the classic version, and `f` for the other version.

**Comment by doxas** [comment]
Implemented!

@illus0r thanks!

**Comment by illus0r** [comment]
@doxas, thank you so much! But it's not at https://twigl.app/ yet, right? I need to deploy it locally to use this new feature?

**Comment by illus0r** [comment]
It works in classic mode, but not in geekest (300 es), where I get ● [ 13:03 ] ERROR: 0:1: 'f' : undeclared identifier

**Comment by doxas** [comment]
@illus0r 

Ohhh ...... I'm so sorry.

It seems that the two modes geeker and geekest were not working properly.
I fixed it and published it.

https://twigl.app/

**Comment by illus0r** [comment]
Already using it! So good!
Thank you very much!
