### ISSUE TITLE
High-resolution screenshot exporting

### ISSUE THREAD

**Issue by XorDev** [doxas/twigl#18]
Would it be possible to get an image export button (perhaps under the dropdown menu in "Download") for exporting high-resolution screenshots? JPEG or PNG (which would be preferable). It could use the same resolution dialogue as with the GIFs and WebM, where you can type in any value you need (ideally up to 8k or so).

That would be perfect for my needs and would help a lot. If I'm dreaming big, I'd also ask for transparency on PNGs and a slider for time so that you can choose exactly when you want to take the screenshot. But I can totally understand if this is beyond the scope of the project. Just the ability to capture screenshots at any resolution will be more than enough.

Thanks!

**Comment by doxas** [comment]
@XorDev 

Hi Xor!
Due to the way twigl works, it doesn't support PNG transparency.
but I was able to meet the other requirements and deployed it for now.

<img width="526" alt="image" src="https://user-images.githubusercontent.com/6252881/147877101-7120aacf-08b7-4356-99d1-6c619b14388f.png">

In my environment, I was able to export at 8k.
you can try it.
https://twigl.app/

**Comment by XorDev** [comment]
Thanks so much! This will be very useful in my showcasing!
